[tool.poetry]
name = "pkns"
version = "0.5.7"
description = "Public Key Name System Framework"
authors = ["Anubhav Mattoo <anubhavmattoo@outlook.com>"]
license = "AGPLv3"

[tool.poetry.dependencies]
python = "^3.6"
daemonocle = "^1.2.3"
pycryptodome = "^3.10.1"
click = "^8.0.1"
sqlitedict = "^1.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
